name: Terraform Plan - Create EKS

on:
  pull_request:
    paths:
      - 'terraform/environments/dev/**'
      - 'terraform/modules/**'
    branches:
      - '**'  # ✅ Run on all branches

jobs:
  create-eks:
    name: Provision EKS Cluster
    runs-on: ubuntu-latest
    environment: dev

    defaults:
      run:
        working-directory: environments/dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Setup Infracost
        uses: infracost/actions/setup@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan (target EKS)
        run: terraform plan -target=module.eks -out=tfplan.binary
      - name: Infracost Breakdown
        run: |
          infracost breakdown \
            --path=. \
            --terraform-plan-file=tfplan.binary \
            --format=json \
            --out-file=infracost.json
        env:
          INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}

      - name: Infracost PR Comment
        run: |
          infracost comment github \
            --path=infracost.json \
            --repo=$GITHUB_REPOSITORY \
            --github-token=${{ secrets.GITHUB_TOKEN }} \
            --pull-request=${{ github.event.pull_request.number }}
        env:
          INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}
