name: Terraform CI & Apply for Dev

on:
  push:
    branches: [main]
  pull_request:
    paths:
      - '**.tf'

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: Terraform Validate & Plan
    runs-on: ubuntu-latest
    environment: dev

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    defaults:
      run:
        shell: bash
        working-directory: environments/dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Check caller identity
        run: aws sts get-caller-identity

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var-file=terraform.tfvars -out=tfplan.binary

      - name: Install Infracost
        uses: infracost/actions/setup@v2

      - name: Run Infracost breakdown
        run: |
          infracost breakdown \
            --path=terraform/environments/dev \
            --terraform-plan-file=tfplan.binary \
            --format=json \
            --out-file=infracost.json
        env:
          INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}

      - name: Upload Terraform Plan (PR only)
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: terraform/environments/dev/tfplan.binary

  apply:
    name: Terraform Apply (Dev)
    runs-on: ubuntu-latest
    needs: terraform
    environment: dev

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    defaults:
      run:
        shell: bash
        working-directory: environments/dev

    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan.binary
